version: "3.7"
services:
  node:
    image: node:12
    volumes:
      - ./:/usr/share/node
    working_dir: /usr/share/node
    environment:
     - NODE_ENV=production
    command: node bin/wwww
    ports:
      - 3000:3000
  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
